export const sBgAmber: string;
export const sBgBlack: string;
export const sBgBlue: string;
export const sBgBlueGrey: string;
export const sBgBrown: string;
export const sBgCyan: string;
export const sBgDeepOrange: string;
export const sBgGreen: string;
export const sBgGrey: string;
export const sBgIndigo: string;
export const sBgLightBlue: string;
export const sBgLightGreen: string;
export const sBgLime: string;
export const sBgOrange: string;
export const sBgPink: string;
export const sBgPurple: string;
export const sBgRed: string;
export const sBgTeal: string;
export const sBgViolet: string;
export const sBgWhite: string;
export const sBgYellow: string;
export const stylesheet: CSSStyleSheet | CSSStyleDeclaration;

export default stylesheet;
